name: Build and Deploy to Railway (railway.app)

on:
  push:
    branches:
    # - 'master'

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup Railway CLI
    - name: Set up Railway CLI
      run: curl -fsSL cli.new | sh

    - name: Deploy
      run: railway up -v
      env: 
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        COMMIT_HASH: ${{ env.GITHUB_SHA }}
        # This should be infered, but let's add it anyways
        RAILWAY_DOCKERFILE_PATH: Dockerfile